### ISSUE TITLE
Customize text label even more

### ISSUE THREAD

**Issue by AlmutawaEssam** [params-ing/StepViewAndroid#10] opened 2020-02-13 15:04 UTC
I think if we had a color for text for each state would be better, like completed, current, un-completed

I'm referring to app:textColorStatus

**Comment by params-ing** [comment] 2021-02-13 00:18
Duplicate of https://github.com/params-ing/StepViewAndroid/issues/1

**Closed as completed by params-ing** 2021-02-13 00:18 UTC
